-- 9 new Italian facilities (IT-001+). Run on existing DB.

alter table public.facilities disable trigger trg_force_pending;

insert into public.facilities
  (id, name, org, type, cc, city, lat, lng, sectors, capabilities, access, equipment, blurb, website, status)
values
  ('IT-001', 'NOI Techpark', 'NOI Techpark Alto Adige', 'Pilot Line / Test Bed', 'IT', 'Bolzano', 46.4779, 11.331, ARRAY['Advanced Materials','Energy & Climate','Advanced Manufacturing']::text[], ARRAY['Characterization & Metrology','Prototyping / Makerspace','Pilot Line / Scale-up']::text[], 'Membership / residency', 'Materials & surface analysis, magnetic, automotive & automation and food-technology labs', 'Innovation park in Bolzano with shared technical labs in materials, automation, energy and food tech, open to companies and startups.', 'noi.bz.it', 'approved'),
  ('IT-002', 'PoliFAB', 'Politecnico di Milano', 'Core Facility', 'IT', 'Milano', 45.478, 9.231, ARRAY['Semiconductors & Photonics','Advanced Materials']::text[], ARRAY['Cleanroom / Nanofab','Characterization & Metrology']::text[], 'Fee-for-service', 'ISO 5/6 cleanroom, photolithography, PVD/CVD thin-film deposition, etching', 'Politecnico di Milano micro- and nanofabrication cleanroom, open to external users on an hourly pay-per-use basis.', 'polifab.polimi.it', 'approved'),
  ('IT-003', 'Fondazione Bruno Kessler (FBK)', 'Fondazione Bruno Kessler', 'Pilot Line / Test Bed', 'IT', 'Trento', 46.0667, 11.15, ARRAY['Semiconductors & Photonics','Quantum']::text[], ARRAY['Cleanroom / Nanofab','Pilot Line / Scale-up','Characterization & Metrology']::text[], 'Collaboration / contract R&D', 'Industrial cleanroom, 6-inch silicon wafer processing, ion implantation, MEMS and sensor foundry', 'Research foundation in Trento offering silicon MEMS and sensor foundry services and co-development to companies.', 'fbk.eu', 'approved'),
  ('IT-004', 'Progetto Manifattura / Industrio', 'Trentino Sviluppo', 'Incubator / Accelerator', 'IT', 'Rovereto', 45.886, 11.043, ARRAY['Advanced Manufacturing','Robotics & Automation']::text[], ARRAY['Prototyping / Makerspace','Pilot Line / Scale-up']::text[], 'Program / cohort', '3D metal and polymer printing, CNC machining, welding stations, automation benches', 'Green-tech and mechatronics accelerator and maker space in Rovereto with prototyping workshops and space for startups.', 'progettomanifattura.it', 'approved'),
  ('IT-005', 'Kilometro Rosso', 'Kilometro Rosso Innovation District', 'Pilot Line / Test Bed', 'IT', 'Bergamo', 45.665, 9.62, ARRAY['Advanced Manufacturing','Space & Aerospace','Robotics & Automation']::text[], ARRAY['Characterization & Metrology','Pilot Line / Scale-up']::text[], 'Fee-for-service', 'Industrial CT scanning, climatic chambers, vibration test benches', 'Science and innovation park near Bergamo offering corporate test services and physical incubation for advanced manufacturing and mobility.', 'kilometrorosso.com', 'approved'),
  ('IT-006', 'Tecnopolo d''Abruzzo', 'Regione Abruzzo', 'Pilot Line / Test Bed', 'IT', 'L''Aquila', 42.35, 13.398, ARRAY['Space & Aerospace','Semiconductors & Photonics']::text[], ARRAY['Characterization & Metrology','Launchpad - Space']::text[], 'Fee-for-service', 'RF/EMC anechoic chambers, thermal-vacuum (TVAC) chambers', 'Technology park in L''Aquila with telecom and space test facilities and on-site incubation.', '', 'approved'),
  ('IT-007', 'Laboratori Nazionali del Gran Sasso (LNGS)', 'INFN', 'Research Institute', 'IT', 'L''Aquila', 42.42, 13.515, ARRAY['Quantum','Energy & Climate']::text[], ARRAY['Characterization & Metrology','Dry Lab']::text[], 'Open user access (proposal)', 'Dilution cryostats (millikelvin), deep underground low-background shielded laboratories', 'INFN national laboratory with deep underground low-radiation facilities and millikelvin cryogenics for quantum and astroparticle experiments, accessed through joint projects.', 'lngs.infn.it', 'approved'),
  ('IT-008', 'BioUpper / BioHubs', 'Cariplo Factory', 'Incubator / Accelerator', 'IT', 'Milano', 45.483, 9.203, ARRAY['Life Sciences & Biotech']::text[], ARRAY['Wet Lab','Biomanufacturing / GMP']::text[], 'Program / cohort', 'Wet lab, Class II hoods, mass spectrometers, bioreactors', 'Life-science and medtech acceleration network in Italy offering wet-lab access and startup programmes through periodic calls.', 'bioupper.com', 'approved'),
  ('IT-009', 'Scientifica Lab Approved', 'Scientifica VC', 'Incubator / Accelerator', 'IT', 'Milano', 45.466, 9.19, ARRAY['Advanced Materials','Advanced Manufacturing']::text[], ARRAY['Prototyping / Makerspace','Characterization & Metrology','Pilot Line / Scale-up']::text[], 'Membership / residency', 'Private national network of advanced industrial machinery for rapid prototyping and characterization', 'Network from Scientifica VC giving its portfolio companies and partners priority access to a private network of advanced industrial machinery across Italy.', 'scientifica.vc', 'approved')
on conflict (id) do nothing;

alter table public.facilities enable trigger trg_force_pending;
