update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Materials"}' where id = 'CH-001';
update public.facilities set sectors = '{"Semiconductors & Photonics","Quantum"}' where id = 'CH-002';
update public.facilities set sectors = '{"Advanced Materials","Biotech & Life Sciences"}' where id = 'CH-003';
update public.facilities set sectors = '{"Advanced Materials","Energy","Semiconductors & Photonics"}' where id = 'CH-004';
update public.facilities set sectors = '{"Biotech & Life Sciences"}' where id = 'CH-005';
update public.facilities set sectors = '{"Advanced Materials","Energy","Cross-sector"}' where id = 'CH-006';
update public.facilities set sectors = '{"Semiconductors & Photonics","Energy","Advanced Manufacturing"}' where id = 'CH-007';
update public.facilities set sectors = '{"Space"}' where id = 'CH-008';
update public.facilities set sectors = '{"Advanced Manufacturing","Energy"}' where id = 'CH-009';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Manufacturing"}' where id = 'DE-001';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Manufacturing"}' where id = 'DE-002';
update public.facilities set sectors = '{"Advanced Materials","Biotech & Life Sciences","Cross-sector"}' where id = 'DE-003';
update public.facilities set sectors = '{"Advanced Materials","Semiconductors & Photonics"}' where id = 'DE-004';
update public.facilities set sectors = '{"Semiconductors & Photonics","Quantum"}' where id = 'DE-005';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Manufacturing"}' where id = 'DE-006';
update public.facilities set sectors = '{"Space","Energy","Advanced Manufacturing"}' where id = 'DE-007';
update public.facilities set sectors = '{"Biotech & Life Sciences","Cross-sector"}' where id = 'DE-008';
update public.facilities set sectors = '{"Advanced Manufacturing","Robotics & Autonomous Systems"}' where id = 'DE-009';
update public.facilities set sectors = '{"Semiconductors & Photonics","Quantum","Advanced Manufacturing"}' where id = 'FR-001';
update public.facilities set sectors = '{"Semiconductors & Photonics","Quantum"}' where id = 'FR-002';
update public.facilities set sectors = '{"Advanced Materials","Biotech & Life Sciences"}' where id = 'FR-003';
update public.facilities set sectors = '{"Energy","Advanced Materials","Advanced Manufacturing"}' where id = 'FR-004';
update public.facilities set sectors = '{"Biotech & Life Sciences","Cross-sector"}' where id = 'FR-005';
update public.facilities set sectors = '{"Biotech & Life Sciences"}' where id = 'FR-006';
update public.facilities set sectors = '{"Space","Defense & Security"}' where id = 'FR-007';
update public.facilities set sectors = '{"Energy","Advanced Materials","Advanced Manufacturing"}' where id = 'FR-008';
update public.facilities set sectors = '{"Robotics & Autonomous Systems","Biotech & Life Sciences"}' where id = 'FR-009';
update public.facilities set sectors = '{"Advanced Materials","Biotech & Life Sciences"}' where id = 'GB-001';
update public.facilities set sectors = '{"Space"}' where id = 'GB-002';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Manufacturing"}' where id = 'GB-003';
update public.facilities set sectors = '{"Biotech & Life Sciences","Semiconductors & Photonics"}' where id = 'GB-004';
update public.facilities set sectors = '{"Advanced Manufacturing","Advanced Materials"}' where id = 'GB-005';
update public.facilities set sectors = '{"Advanced Materials","Biotech & Life Sciences","Advanced Manufacturing"}' where id = 'GB-006';
update public.facilities set sectors = '{"Energy","Robotics & Autonomous Systems"}' where id = 'GB-007';
update public.facilities set sectors = '{"Biotech & Life Sciences"}' where id = 'GB-008';
update public.facilities set sectors = '{"Biotech & Life Sciences","Robotics & Autonomous Systems","Cross-sector"}' where id = 'GB-009';
update public.facilities set sectors = '{"Advanced Materials","Energy","Semiconductors & Photonics"}' where id = 'GB-010';
update public.facilities set sectors = '{"Space"}' where id = 'NL-001';
update public.facilities set sectors = '{"Semiconductors & Photonics","Quantum"}' where id = 'NL-002';
update public.facilities set sectors = '{"Quantum","Semiconductors & Photonics"}' where id = 'NL-003';
update public.facilities set sectors = '{"Semiconductors & Photonics","Energy","Advanced Manufacturing"}' where id = 'NL-004';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Manufacturing"}' where id = 'NL-005';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Manufacturing"}' where id = 'NL-006';
update public.facilities set sectors = '{"Biotech & Life Sciences","Quantum"}' where id = 'NL-007';
update public.facilities set sectors = '{"Semiconductors & Photonics","Space","Advanced Manufacturing"}' where id = 'NL-008';
update public.facilities set sectors = '{"Advanced Materials","Energy","Advanced Manufacturing"}' where id = 'NL-009';
update public.facilities set sectors = '{"Advanced Materials","Space","Energy"}' where id = 'GB-011';
update public.facilities set sectors = '{"Advanced Materials","Biotech & Life Sciences"}' where id = 'GB-012';
update public.facilities set sectors = '{"Advanced Materials","Quantum","Semiconductors & Photonics"}' where id = 'GB-013';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Materials","Quantum"}' where id = 'GB-014';
update public.facilities set sectors = '{"Advanced Materials","Energy"}' where id = 'GB-015';
update public.facilities set sectors = '{"Advanced Materials","Energy"}' where id = 'GB-016';
update public.facilities set sectors = '{"Advanced Materials","Energy"}' where id = 'GB-017';
update public.facilities set sectors = '{"Advanced Materials","Energy","Semiconductors & Photonics"}' where id = 'GB-018';
update public.facilities set sectors = '{"Semiconductors & Photonics","Quantum","Advanced Materials"}' where id = 'GB-019';
update public.facilities set sectors = '{"Advanced Materials","Semiconductors & Photonics"}' where id = 'GB-020';
update public.facilities set sectors = '{"Quantum","Semiconductors & Photonics","Advanced Materials"}' where id = 'GB-021';
update public.facilities set sectors = '{"Advanced Materials","Advanced Manufacturing"}' where id = 'GB-022';
update public.facilities set sectors = '{"Advanced Materials","Semiconductors & Photonics"}' where id = 'GB-023';
update public.facilities set sectors = '{"Semiconductors & Photonics","Quantum","Advanced Materials"}' where id = 'GB-024';
update public.facilities set sectors = '{"Advanced Materials","Quantum","Semiconductors & Photonics"}' where id = 'GB-025';
update public.facilities set sectors = '{"Advanced Materials","Energy"}' where id = 'GB-026';
update public.facilities set sectors = '{"Advanced Materials","Biotech & Life Sciences","Energy"}' where id = 'GB-027';
update public.facilities set sectors = '{"Advanced Materials","Biotech & Life Sciences"}' where id = 'GB-028';
update public.facilities set sectors = '{"Advanced Materials","Biotech & Life Sciences"}' where id = 'GB-029';
update public.facilities set sectors = '{"Advanced Materials","Biotech & Life Sciences"}' where id = 'GB-030';
update public.facilities set sectors = '{"Energy","Advanced Materials"}' where id = 'GB-031';
update public.facilities set sectors = '{"Advanced Materials","Semiconductors & Photonics","Quantum"}' where id = 'GB-032';
update public.facilities set sectors = '{"Advanced Materials","Semiconductors & Photonics","Biotech & Life Sciences"}' where id = 'GB-033';
update public.facilities set sectors = '{"Advanced Materials","Advanced Manufacturing","Biotech & Life Sciences"}' where id = 'GB-034';
update public.facilities set sectors = '{"Advanced Materials","Semiconductors & Photonics","Agrifood"}' where id = 'GB-035';
update public.facilities set sectors = '{"Advanced Materials","Semiconductors & Photonics","Energy"}' where id = 'GB-036';
update public.facilities set sectors = '{"Advanced Materials","Advanced Manufacturing","Energy"}' where id = 'GB-037';
update public.facilities set sectors = '{"Advanced Materials","Energy"}' where id = 'GB-038';
update public.facilities set sectors = '{"Biotech & Life Sciences","Advanced Materials"}' where id = 'GB-039';
update public.facilities set sectors = '{"Advanced Materials","Energy","Semiconductors & Photonics"}' where id = 'GB-040';
update public.facilities set sectors = '{"Semiconductors & Photonics","Quantum","Advanced Materials"}' where id = 'GB-041';
update public.facilities set sectors = '{"Advanced Materials","Energy"}' where id = 'GB-042';
update public.facilities set sectors = '{"Energy","Advanced Materials"}' where id = 'GB-043';
update public.facilities set sectors = '{"Advanced Materials","Advanced Manufacturing","Biotech & Life Sciences"}' where id = 'GB-044';
update public.facilities set sectors = '{"Advanced Materials","Advanced Manufacturing","Space"}' where id = 'GB-045';
update public.facilities set sectors = '{"Advanced Materials","Biotech & Life Sciences"}' where id = 'GB-046';
update public.facilities set sectors = '{"Advanced Materials","Advanced Manufacturing"}' where id = 'GB-047';
update public.facilities set sectors = '{"Advanced Materials","Advanced Manufacturing"}' where id = 'GB-048';
update public.facilities set sectors = '{"Biotech & Life Sciences","Cross-sector"}' where id = 'GB-049';
update public.facilities set sectors = '{"Biotech & Life Sciences","Advanced Materials","Cross-sector"}' where id = 'GB-050';
update public.facilities set sectors = '{"Biotech & Life Sciences","Advanced Materials","Cross-sector"}' where id = 'GB-051';
update public.facilities set sectors = '{"Energy","Advanced Materials","Climate & Carbon Capture"}' where id = 'GB-052';
update public.facilities set sectors = '{"Semiconductors & Photonics","Quantum","Advanced Materials"}' where id = 'GB-053';
update public.facilities set sectors = '{"Semiconductors & Photonics","Quantum"}' where id = 'GB-054';
update public.facilities set sectors = '{"Semiconductors & Photonics","Quantum","Advanced Manufacturing"}' where id = 'GB-055';
update public.facilities set sectors = '{"Semiconductors & Photonics","Quantum","Advanced Materials"}' where id = 'GB-056';
update public.facilities set sectors = '{"Semiconductors & Photonics"}' where id = 'GB-057';
update public.facilities set sectors = '{"Quantum","Semiconductors & Photonics","Advanced Materials"}' where id = 'GB-058';
update public.facilities set sectors = '{"Advanced Manufacturing","Robotics & Autonomous Systems","Advanced Materials"}' where id = 'GB-059';
update public.facilities set sectors = '{"Advanced Manufacturing","Robotics & Autonomous Systems"}' where id = 'GB-060';
update public.facilities set sectors = '{"Advanced Manufacturing","Energy","Robotics & Autonomous Systems"}' where id = 'GB-061';
update public.facilities set sectors = '{"Advanced Manufacturing","Advanced Materials"}' where id = 'GB-062';
update public.facilities set sectors = '{"Advanced Manufacturing","Energy"}' where id = 'GB-063';
update public.facilities set sectors = '{"Energy"}' where id = 'GB-064';
update public.facilities set sectors = '{"Energy","Robotics & Autonomous Systems","Mobility"}' where id = 'GB-065';
update public.facilities set sectors = '{"Robotics & Autonomous Systems","Energy"}' where id = 'GB-066';
update public.facilities set sectors = '{"Biotech & Life Sciences"}' where id = 'GB-067';
update public.facilities set sectors = '{"Robotics & Autonomous Systems","Cross-sector"}' where id = 'GB-068';
update public.facilities set sectors = '{"Advanced Materials","Quantum","Energy"}' where id = 'GB-069';
update public.facilities set sectors = '{"Advanced Materials","Biotech & Life Sciences","Energy"}' where id = 'GB-070';
update public.facilities set sectors = '{"Biotech & Life Sciences"}' where id = 'GB-071';
update public.facilities set sectors = '{"Biotech & Life Sciences","Cross-sector"}' where id = 'GB-072';
update public.facilities set sectors = '{"Biotech & Life Sciences","Computing & HPC"}' where id = 'GB-073';
update public.facilities set sectors = '{"Biotech & Life Sciences"}' where id = 'GB-074';
update public.facilities set sectors = '{"Biotech & Life Sciences","Cross-sector"}' where id = 'GB-075';
update public.facilities set sectors = '{"Biotech & Life Sciences","Cross-sector"}' where id = 'GB-076';
update public.facilities set sectors = '{"Biotech & Life Sciences","Cross-sector"}' where id = 'GB-077';
update public.facilities set sectors = '{"Biotech & Life Sciences","Cross-sector"}' where id = 'GB-078';
update public.facilities set sectors = '{"Biotech & Life Sciences","Cross-sector"}' where id = 'GB-079';
update public.facilities set sectors = '{"Biotech & Life Sciences","Cross-sector"}' where id = 'GB-080';
update public.facilities set sectors = '{"Biotech & Life Sciences","Agrifood","Cross-sector"}' where id = 'GB-081';
update public.facilities set sectors = '{"Advanced Materials","Biotech & Life Sciences"}' where id = 'GB-082';
update public.facilities set sectors = '{"Advanced Materials","Energy","Advanced Manufacturing"}' where id = 'IT-001';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Materials"}' where id = 'IT-002';
update public.facilities set sectors = '{"Semiconductors & Photonics","Quantum","Advanced Manufacturing"}' where id = 'IT-003';
update public.facilities set sectors = '{"Advanced Manufacturing","Robotics & Autonomous Systems","Advanced Materials"}' where id = 'IT-004';
update public.facilities set sectors = '{"Advanced Manufacturing","Space","Robotics & Autonomous Systems"}' where id = 'IT-005';
update public.facilities set sectors = '{"Space","Semiconductors & Photonics"}' where id = 'IT-006';
update public.facilities set sectors = '{"Quantum","Energy"}' where id = 'IT-007';
update public.facilities set sectors = '{"Biotech & Life Sciences","Cross-sector"}' where id = 'IT-008';
update public.facilities set sectors = '{"Advanced Materials","Advanced Manufacturing"}' where id = 'IT-009';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Materials","Energy"}' where id = 'DE-010';
update public.facilities set sectors = '{"Semiconductors & Photonics","Quantum","Advanced Manufacturing"}' where id = 'DE-011';
update public.facilities set sectors = '{"Semiconductors & Photonics","Quantum","Advanced Manufacturing"}' where id = 'DE-012';
update public.facilities set sectors = '{"Quantum","Semiconductors & Photonics","Advanced Manufacturing"}' where id = 'DE-013';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Manufacturing"}' where id = 'DE-014';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Manufacturing","Space"}' where id = 'DE-015';
update public.facilities set sectors = '{"Advanced Manufacturing","Semiconductors & Photonics","Advanced Materials"}' where id = 'DE-016';
update public.facilities set sectors = '{"Advanced Manufacturing","Advanced Materials"}' where id = 'DE-017';
update public.facilities set sectors = '{"Advanced Materials","Advanced Manufacturing","Robotics & Autonomous Systems"}' where id = 'DE-018';
update public.facilities set sectors = '{"Advanced Manufacturing","Robotics & Autonomous Systems"}' where id = 'DE-019';
update public.facilities set sectors = '{"Robotics & Autonomous Systems","Advanced Manufacturing","Applied AI & ML"}' where id = 'DE-020';
update public.facilities set sectors = '{"Advanced Materials","Energy","Advanced Manufacturing"}' where id = 'DE-021';
update public.facilities set sectors = '{"Energy","Advanced Materials","Advanced Manufacturing"}' where id = 'DE-022';
update public.facilities set sectors = '{"Energy","Advanced Materials","Advanced Manufacturing"}' where id = 'DE-023';
update public.facilities set sectors = '{"Energy","Semiconductors & Photonics","Advanced Materials"}' where id = 'DE-024';
update public.facilities set sectors = '{"Biotech & Life Sciences"}' where id = 'DE-025';
update public.facilities set sectors = '{"Biotech & Life Sciences","Cross-sector"}' where id = 'DE-026';
update public.facilities set sectors = '{"Biotech & Life Sciences","Cross-sector"}' where id = 'DE-027';
update public.facilities set sectors = '{"Space","Advanced Materials"}' where id = 'DE-028';
update public.facilities set sectors = '{"Space","Robotics & Autonomous Systems"}' where id = 'DE-029';
update public.facilities set sectors = '{"Space","Advanced Manufacturing","Applied AI & ML"}' where id = 'DE-030';
update public.facilities set sectors = '{"Semiconductors & Photonics","Quantum","Advanced Manufacturing"}' where id = 'BE-001';
update public.facilities set sectors = '{"Semiconductors & Photonics","Quantum","Advanced Manufacturing"}' where id = 'BE-002';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Manufacturing","Robotics & Autonomous Systems"}' where id = 'BE-003';
update public.facilities set sectors = '{"Energy","Advanced Materials","Semiconductors & Photonics"}' where id = 'BE-004';
update public.facilities set sectors = '{"Advanced Manufacturing","Robotics & Autonomous Systems"}' where id = 'BE-005';
update public.facilities set sectors = '{"Advanced Manufacturing","Robotics & Autonomous Systems","Advanced Materials"}' where id = 'BE-006';
update public.facilities set sectors = '{"Space","Energy","Advanced Manufacturing"}' where id = 'BE-007';
update public.facilities set sectors = '{"Energy","Advanced Materials","Biotech & Life Sciences"}' where id = 'BE-008';
update public.facilities set sectors = '{"Advanced Materials","Energy","Advanced Manufacturing"}' where id = 'BE-009';
update public.facilities set sectors = '{"Advanced Materials","Energy","Advanced Manufacturing"}' where id = 'BE-010';
update public.facilities set sectors = '{"Semiconductors & Photonics","Robotics & Autonomous Systems"}' where id = 'BE-011';
update public.facilities set sectors = '{"Biotech & Life Sciences","Cross-sector"}' where id = 'BE-012';
update public.facilities set sectors = '{"Biotech & Life Sciences","Cross-sector"}' where id = 'BE-013';
update public.facilities set sectors = '{"Biotech & Life Sciences","Cross-sector"}' where id = 'BE-014';
update public.facilities set sectors = '{"Space","Cross-sector"}' where id = 'BE-015';
update public.facilities set sectors = '{"Advanced Manufacturing","Biotech & Life Sciences"}' where id = 'BE-016';
update public.facilities set sectors = '{"Semiconductors & Photonics","Quantum","Advanced Materials"}' where id = 'DK-001';
update public.facilities set sectors = '{"Biotech & Life Sciences","Advanced Materials","Agrifood"}' where id = 'DK-002';
update public.facilities set sectors = '{"Advanced Manufacturing","Biotech & Life Sciences","Energy"}' where id = 'DK-003';
update public.facilities set sectors = '{"Space","Semiconductors & Photonics"}' where id = 'DK-004';
update public.facilities set sectors = '{"Biotech & Life Sciences","Quantum"}' where id = 'DK-005';
update public.facilities set sectors = '{"Biotech & Life Sciences","Cross-sector"}' where id = 'DK-006';
update public.facilities set sectors = '{"Quantum"}' where id = 'DK-007';
update public.facilities set sectors = '{"Advanced Materials","Advanced Manufacturing","Biotech & Life Sciences"}' where id = 'DK-008';
update public.facilities set sectors = '{"Robotics & Autonomous Systems","Advanced Manufacturing"}' where id = 'DK-009';
update public.facilities set sectors = '{"Biotech & Life Sciences"}' where id = 'DK-010';
update public.facilities set sectors = '{"Advanced Materials","Semiconductors & Photonics","Biotech & Life Sciences"}' where id = 'DK-011';
update public.facilities set sectors = '{"Advanced Materials","Energy","Advanced Manufacturing"}' where id = 'DK-012';
update public.facilities set sectors = '{"Energy","Advanced Materials","Advanced Manufacturing"}' where id = 'DK-013';
update public.facilities set sectors = '{"Energy","Advanced Materials","Advanced Manufacturing"}' where id = 'DK-014';
update public.facilities set sectors = '{"Space","Cross-sector"}' where id = 'DK-015';
update public.facilities set sectors = '{"Semiconductors & Photonics","Biotech & Life Sciences","Advanced Materials"}' where id = 'PL-001';
update public.facilities set sectors = '{"Advanced Materials","Biotech & Life Sciences","Semiconductors & Photonics"}' where id = 'PL-002';
update public.facilities set sectors = '{"Advanced Materials","Semiconductors & Photonics","Biotech & Life Sciences"}' where id = 'PL-003';
update public.facilities set sectors = '{"Advanced Materials","Semiconductors & Photonics","Quantum"}' where id = 'PL-004';
update public.facilities set sectors = '{"Semiconductors & Photonics","Space","Advanced Materials"}' where id = 'PL-005';
update public.facilities set sectors = '{"Biotech & Life Sciences","Cross-sector"}' where id = 'PL-006';
update public.facilities set sectors = '{"Biotech & Life Sciences","Advanced Materials","Advanced Manufacturing"}' where id = 'PL-007';
update public.facilities set sectors = '{"Space","Advanced Manufacturing","Advanced Materials"}' where id = 'PL-008';
update public.facilities set sectors = '{"Advanced Materials","Energy","Advanced Manufacturing"}' where id = 'PL-009';
update public.facilities set sectors = '{"Advanced Materials","Advanced Manufacturing"}' where id = 'PL-010';
update public.facilities set sectors = '{"Robotics & Autonomous Systems","Advanced Manufacturing"}' where id = 'PL-011';
update public.facilities set sectors = '{"Biotech & Life Sciences","Advanced Materials"}' where id = 'PL-012';
update public.facilities set sectors = '{"Advanced Manufacturing","Robotics & Autonomous Systems","Energy"}' where id = 'PL-013';
update public.facilities set sectors = '{"Space","Mobility","Cross-sector"}' where id = 'PL-014';
update public.facilities set sectors = '{"Space","Quantum","Advanced Manufacturing"}' where id = 'PL-015';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Materials","Quantum"}' where id = 'LT-001';
update public.facilities set sectors = '{"Biotech & Life Sciences"}' where id = 'LT-002';
update public.facilities set sectors = '{"Advanced Materials","Energy","Advanced Manufacturing"}' where id = 'LT-003';
update public.facilities set sectors = '{"Advanced Manufacturing","Robotics & Autonomous Systems"}' where id = 'LT-004';
update public.facilities set sectors = '{"Biotech & Life Sciences","Advanced Materials","Advanced Manufacturing"}' where id = 'EE-001';
update public.facilities set sectors = '{"Space","Advanced Manufacturing","Semiconductors & Photonics"}' where id = 'EE-002';
update public.facilities set sectors = '{"Advanced Manufacturing","Robotics & Autonomous Systems"}' where id = 'EE-003';
update public.facilities set sectors = '{"Biotech & Life Sciences","Energy","Cross-sector"}' where id = 'EE-004';
update public.facilities set sectors = '{"Space","Cross-sector"}' where id = 'EE-005';
update public.facilities set sectors = '{"Biotech & Life Sciences","Cross-sector"}' where id = 'EE-006';
update public.facilities set sectors = '{"Advanced Materials","Semiconductors & Photonics","Energy"}' where id = 'LV-001';
update public.facilities set sectors = '{"Biotech & Life Sciences"}' where id = 'LV-002';
update public.facilities set sectors = '{"Biotech & Life Sciences","Advanced Materials","Advanced Manufacturing"}' where id = 'LV-003';
update public.facilities set sectors = '{"Advanced Manufacturing","Advanced Materials"}' where id = 'LV-004';
update public.facilities set sectors = '{"Space"}' where id = 'NO-001';
update public.facilities set sectors = '{"Space"}' where id = 'SE-001';
update public.facilities set sectors = '{"Space"}' where id = 'GB-083';
update public.facilities set sectors = '{"Space"}' where id = 'GB-084';
update public.facilities set sectors = '{"Space"}' where id = 'PT-001';
update public.facilities set sectors = '{"Quantum"}' where id = 'DE-031';
update public.facilities set sectors = '{"Quantum","Computing & HPC"}' where id = 'DE-032';
update public.facilities set sectors = '{"Quantum"}' where id = 'NL-010';
update public.facilities set sectors = '{"Quantum","Computing & HPC"}' where id = 'FI-001';
update public.facilities set sectors = '{"Quantum"}' where id = 'SE-002';
update public.facilities set sectors = '{"Quantum","Computing & HPC","Semiconductors & Photonics"}' where id = 'PL-016';
update public.facilities set sectors = '{"Quantum","Computing & HPC"}' where id = 'FR-010';
update public.facilities set sectors = '{"Quantum","Computing & HPC"}' where id = 'CZ-001';
update public.facilities set sectors = '{"Energy"}' where id = 'CH-010';
update public.facilities set sectors = '{"Energy"}' where id = 'DE-033';
update public.facilities set sectors = '{"Energy"}' where id = 'DE-034';
update public.facilities set sectors = '{"Energy","Advanced Materials"}' where id = 'NL-011';
update public.facilities set sectors = '{"Energy"}' where id = 'IT-010';
update public.facilities set sectors = '{"Energy"}' where id = 'ES-001';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Materials"}' where id = 'FR-011';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Manufacturing"}' where id = 'FR-012';
update public.facilities set sectors = '{"Semiconductors & Photonics","Biotech & Life Sciences"}' where id = 'FR-013';
update public.facilities set sectors = '{"Advanced Materials","Semiconductors & Photonics"}' where id = 'FR-014';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Materials"}' where id = 'FR-015';
update public.facilities set sectors = '{"Advanced Materials","Biotech & Life Sciences","Energy"}' where id = 'FR-016';
update public.facilities set sectors = '{"Advanced Materials","Energy","Biotech & Life Sciences"}' where id = 'FR-017';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Materials"}' where id = 'FR-018';
update public.facilities set sectors = '{"Quantum","Computing & HPC","Semiconductors & Photonics"}' where id = 'FR-019';
update public.facilities set sectors = '{"Robotics & Autonomous Systems","Advanced Manufacturing"}' where id = 'FR-020';
update public.facilities set sectors = '{"Space","Advanced Manufacturing"}' where id = 'FR-021';
update public.facilities set sectors = '{"Space","Advanced Materials","Advanced Manufacturing"}' where id = 'FR-022';
update public.facilities set sectors = '{"Biotech & Life Sciences","Advanced Manufacturing","Semiconductors & Photonics"}' where id = 'FR-023';
update public.facilities set sectors = '{"Semiconductors & Photonics","Quantum"}' where id = 'FR-024';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Manufacturing"}' where id = 'FR-025';
update public.facilities set sectors = '{"Biotech & Life Sciences","Energy","Advanced Manufacturing"}' where id = 'FR-026';
update public.facilities set sectors = '{"Biotech & Life Sciences","Semiconductors & Photonics","Advanced Manufacturing"}' where id = 'FR-027';
update public.facilities set sectors = '{"Biotech & Life Sciences","Advanced Manufacturing"}' where id = 'FR-028';
update public.facilities set sectors = '{"Biotech & Life Sciences"}' where id = 'FR-029';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Materials","Quantum"}' where id = 'NL-012';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Materials","Quantum"}' where id = 'NL-013';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Materials","Quantum"}' where id = 'NL-014';
update public.facilities set sectors = '{"Semiconductors & Photonics","Quantum","Energy"}' where id = 'NL-015';
update public.facilities set sectors = '{"Robotics & Autonomous Systems","Advanced Manufacturing","Agrifood"}' where id = 'NL-016';
update public.facilities set sectors = '{"Biotech & Life Sciences","Semiconductors & Photonics","Cross-sector"}' where id = 'NL-017';
update public.facilities set sectors = '{"Biotech & Life Sciences","Cross-sector"}' where id = 'NL-018';
update public.facilities set sectors = '{"Biotech & Life Sciences","Semiconductors & Photonics","Cross-sector"}' where id = 'CH-011';
update public.facilities set sectors = '{"Biotech & Life Sciences"}' where id = 'CH-012';
update public.facilities set sectors = '{"Advanced Materials","Advanced Manufacturing","Energy"}' where id = 'CH-013';
update public.facilities set sectors = '{"Biotech & Life Sciences","Robotics & Autonomous Systems"}' where id = 'CH-014';
update public.facilities set sectors = '{"Robotics & Autonomous Systems","Space","Advanced Manufacturing"}' where id = 'CH-015';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Manufacturing","Advanced Materials"}' where id = 'CH-016';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Manufacturing","Advanced Materials"}' where id = 'CH-017';
update public.facilities set sectors = '{"Advanced Materials","Biotech & Life Sciences","Semiconductors & Photonics"}' where id = 'IT-011';
update public.facilities set sectors = '{"Advanced Materials","Semiconductors & Photonics","Quantum"}' where id = 'IT-012';
update public.facilities set sectors = '{"Biotech & Life Sciences","Advanced Materials","Robotics & Autonomous Systems"}' where id = 'IT-013';
update public.facilities set sectors = '{"Biotech & Life Sciences"}' where id = 'IT-014';
update public.facilities set sectors = '{"Robotics & Autonomous Systems","Advanced Materials","Biotech & Life Sciences"}' where id = 'IT-015';
update public.facilities set sectors = '{"Advanced Manufacturing","Energy","Biotech & Life Sciences"}' where id = 'IT-016';
update public.facilities set sectors = '{"Semiconductors & Photonics","Quantum","Advanced Materials"}' where id = 'IE-001';
update public.facilities set sectors = '{"Biotech & Life Sciences","Advanced Manufacturing"}' where id = 'IE-002';
update public.facilities set sectors = '{"Advanced Materials","Semiconductors & Photonics","Biotech & Life Sciences"}' where id = 'IE-003';
update public.facilities set sectors = '{"Semiconductors & Photonics","Robotics & Autonomous Systems"}' where id = 'IE-004';
update public.facilities set sectors = '{"Advanced Manufacturing","Robotics & Autonomous Systems"}' where id = 'IE-005';
update public.facilities set sectors = '{"Biotech & Life Sciences","Advanced Materials","Advanced Manufacturing"}' where id = 'IE-006';
update public.facilities set sectors = '{"Biotech & Life Sciences","Advanced Materials","Robotics & Autonomous Systems"}' where id = 'IE-007';
update public.facilities set sectors = '{"Space","Cross-sector"}' where id = 'IE-008';
update public.facilities set sectors = '{"Advanced Materials","Semiconductors & Photonics","Biotech & Life Sciences"}' where id = 'PT-002';
update public.facilities set sectors = '{"Semiconductors & Photonics","Biotech & Life Sciences","Advanced Materials"}' where id = 'PT-003';
update public.facilities set sectors = '{"Robotics & Autonomous Systems","Advanced Manufacturing","Semiconductors & Photonics"}' where id = 'PT-004';
update public.facilities set sectors = '{"Robotics & Autonomous Systems","Biotech & Life Sciences","Advanced Manufacturing"}' where id = 'PT-005';
update public.facilities set sectors = '{"Biotech & Life Sciences","Advanced Manufacturing","Cross-sector"}' where id = 'PT-006';
update public.facilities set sectors = '{"Space","Advanced Manufacturing","Robotics & Autonomous Systems"}' where id = 'PT-007';
update public.facilities set sectors = '{"Space","Cross-sector"}' where id = 'PT-008';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Materials","Advanced Manufacturing"}' where id = 'AT-001';
update public.facilities set sectors = '{"Energy","Advanced Materials","Robotics & Autonomous Systems"}' where id = 'AT-002';
update public.facilities set sectors = '{"Semiconductors & Photonics","Quantum","Advanced Materials"}' where id = 'AT-003';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Materials","Advanced Manufacturing"}' where id = 'AT-004';
update public.facilities set sectors = '{"Advanced Materials","Advanced Manufacturing","Semiconductors & Photonics"}' where id = 'AT-005';
update public.facilities set sectors = '{"Advanced Materials","Advanced Manufacturing","Energy"}' where id = 'AT-006';
update public.facilities set sectors = '{"Biotech & Life Sciences","Robotics & Autonomous Systems"}' where id = 'AT-007';
update public.facilities set sectors = '{"Space","Cross-sector"}' where id = 'AT-008';
update public.facilities set sectors = '{"Semiconductors & Photonics","Quantum","Advanced Materials"}' where id = 'SE-003';
update public.facilities set sectors = '{"Semiconductors & Photonics","Quantum","Advanced Materials"}' where id = 'SE-004';
update public.facilities set sectors = '{"Semiconductors & Photonics","Quantum","Advanced Materials"}' where id = 'SE-005';
update public.facilities set sectors = '{"Advanced Materials","Biotech & Life Sciences","Energy"}' where id = 'SE-006';
update public.facilities set sectors = '{"Biotech & Life Sciences"}' where id = 'SE-007';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Manufacturing","Advanced Materials"}' where id = 'SE-008';
update public.facilities set sectors = '{"Robotics & Autonomous Systems","Advanced Manufacturing"}' where id = 'SE-009';
update public.facilities set sectors = '{"Space","Cross-sector"}' where id = 'SE-010';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Materials","Advanced Manufacturing"}' where id = 'ES-002';
update public.facilities set sectors = '{"Advanced Materials","Biotech & Life Sciences","Energy"}' where id = 'ES-003';
update public.facilities set sectors = '{"Advanced Materials","Semiconductors & Photonics"}' where id = 'ES-004';
update public.facilities set sectors = '{"Semiconductors & Photonics","Quantum","Space"}' where id = 'ES-005';
update public.facilities set sectors = '{"Advanced Materials","Semiconductors & Photonics"}' where id = 'ES-006';
update public.facilities set sectors = '{"Biotech & Life Sciences","Advanced Materials"}' where id = 'ES-007';
update public.facilities set sectors = '{"Energy","Advanced Materials","Advanced Manufacturing"}' where id = 'ES-008';
update public.facilities set sectors = '{"Advanced Manufacturing","Advanced Materials","Robotics & Autonomous Systems"}' where id = 'ES-009';
update public.facilities set sectors = '{"Advanced Materials","Biotech & Life Sciences","Advanced Manufacturing"}' where id = 'ES-010';
update public.facilities set sectors = '{"Advanced Manufacturing","Advanced Materials","Robotics & Autonomous Systems"}' where id = 'ES-011';
update public.facilities set sectors = '{"Advanced Materials","Advanced Manufacturing","Space"}' where id = 'ES-012';
update public.facilities set sectors = '{"Advanced Materials","Semiconductors & Photonics"}' where id = 'ES-013';
update public.facilities set sectors = '{"Biotech & Life Sciences","Cross-sector"}' where id = 'ES-014';
update public.facilities set sectors = '{"Space","Robotics & Autonomous Systems"}' where id = 'ES-015';
update public.facilities set sectors = '{"Space","Cross-sector"}' where id = 'ES-016';
update public.facilities set sectors = '{"Semiconductors & Photonics","Quantum","Advanced Materials"}' where id = 'FI-002';
update public.facilities set sectors = '{"Semiconductors & Photonics","Quantum","Advanced Manufacturing"}' where id = 'FI-003';
update public.facilities set sectors = '{"Advanced Materials","Energy","Biotech & Life Sciences"}' where id = 'FI-004';
update public.facilities set sectors = '{"Advanced Manufacturing","Advanced Materials","Semiconductors & Photonics"}' where id = 'FI-005';
update public.facilities set sectors = '{"Advanced Manufacturing","Advanced Materials","Semiconductors & Photonics"}' where id = 'FI-006';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Materials","Biotech & Life Sciences"}' where id = 'FI-007';
update public.facilities set sectors = '{"Semiconductors & Photonics","Robotics & Autonomous Systems","Space"}' where id = 'FI-008';
update public.facilities set sectors = '{"Space","Cross-sector"}' where id = 'FI-009';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Materials","Quantum"}' where id = 'NO-002';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Materials","Quantum"}' where id = 'NO-003';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Materials","Biotech & Life Sciences"}' where id = 'NO-004';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Materials","Advanced Manufacturing"}' where id = 'NO-005';
update public.facilities set sectors = '{"Energy","Advanced Materials","Advanced Manufacturing"}' where id = 'NO-006';
update public.facilities set sectors = '{"Energy","Advanced Materials","Advanced Manufacturing"}' where id = 'NO-007';
update public.facilities set sectors = '{"Advanced Manufacturing","Energy","Robotics & Autonomous Systems"}' where id = 'NO-008';
update public.facilities set sectors = '{"Energy","Advanced Materials","Climate & Carbon Capture"}' where id = 'NO-009';
update public.facilities set sectors = '{"Biotech & Life Sciences","Cross-sector"}' where id = 'NO-010';
update public.facilities set sectors = '{"Advanced Materials","Advanced Manufacturing"}' where id = 'NO-011';
update public.facilities set sectors = '{"Advanced Materials","Semiconductors & Photonics","Quantum"}' where id = 'CZ-002';
update public.facilities set sectors = '{"Advanced Materials","Semiconductors & Photonics","Quantum"}' where id = 'CZ-003';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Materials","Biotech & Life Sciences"}' where id = 'CZ-004';
update public.facilities set sectors = '{"Semiconductors & Photonics","Advanced Manufacturing","Advanced Materials"}' where id = 'CZ-005';
update public.facilities set sectors = '{"Biotech & Life Sciences"}' where id = 'CZ-006';
update public.facilities set sectors = '{"Biotech & Life Sciences","Applied AI & ML"}' where id = 'CZ-007';
update public.facilities set sectors = '{"Advanced Materials","Biotech & Life Sciences","Energy"}' where id = 'CZ-008';
update public.facilities set sectors = '{"Space","Cross-sector"}' where id = 'CZ-009';
